import path from "path";
import { configExistsMessage } from "../utils/breadcrumbs";
import { SiloError } from "../utils/errors";

const INIT_TEMPLATE = `# Generated by silo init
# Docs: silo doc config

version = 1

[ports]
WEB_PORT = 3000
API_PORT = 8080
REDIS_PORT = 6379
TILT_PORT = 10350

[hosts]
APP_HOST = "\${name}.localhost"
API_HOST = "api.\${name}.localhost"

# Optional k3d integration (uncomment to enable)
# [k3d]
# enabled = true
#
# [k3d.registry]
# enabled = true
`;

const BANNER = `      __               ____  _ _
     /  \\             / ___|| (_) ___
    /____\\            \\___ \\| | |/ _ \\
    | [] |             ___) | | | (_) |
    |    |            |____/|_|_|\\___/
    |    |
    |____|
~~~~|____|~~~~~`;

export const init = async (options: { config: string }): Promise<void> => {
  const resolvedPath = path.resolve(process.cwd(), options.config);
  const configFile = Bun.file(resolvedPath);
  if (await configFile.exists()) {
    throw new SiloError(configExistsMessage(resolvedPath), "CONFIG_EXISTS");
  }

  await Bun.write(resolvedPath, INIT_TEMPLATE);

  console.log(BANNER);
  console.log("");
  console.log("silo init - isolate your dev worlds.");
  console.log("");
  console.log(
    '"War. War never changes. But your localhost can." - Silo Overseer'
  );
  console.log("");
  console.log(
    "silo generates a silo.toml that defines ports, hosts, and optional k3d settings."
  );
  console.log("Next: edit the file, then run `silo up`.");
};
